# -*- coding: utf-8 -*-
"""finalproject (5).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Gr8O2iYZFNjabaUMWvQmZj-tb7PpJScg
"""

!pip install ultralytics

# Core imports
import os
import cv2
import numpy as np
import pandas as pd

# Visualization
import matplotlib.pyplot as plt
from tqdm import tqdm

from ultralytics import YOLO

"""!pip install ultralytics"""

DATASET_PATH = "/kaggle/input/traffic-video-dataset"

videos = []
for root, dirs, files in os.walk(DATASET_PATH):
    for file in files:
        if file.endswith(".mp4"):
            videos.append(os.path.join(root, file))

print("Total videos:", len(videos))
print("Sample videos:", videos[:3])

def sample_frames(video_path, sample_every_sec=1):
    cap = cv2.VideoCapture(video_path)
    fps = int(cap.get(cv2.CAP_PROP_FPS))

    frames = []
    frame_id = 0

    while True:
        ret, frame = cap.read()
        if not ret:
            break

        if frame_id % (fps * sample_every_sec) == 0:
            frames.append(frame)

        frame_id += 1

    cap.release()
    return frames, fps


for video in videos:
    frames, fps = sample_frames(video, 1)



print("Sampled frames:", len(frames))
print("FPS:", fps)

def crop_roi(frame, y1=120):
    h, w = frame.shape[:2]
    return frame[y1:h, 0:w]

model = YOLO("yolov8x.pt")

VEHICLE_CLASSES = [2, 3, 5, 7]  # car, motorcycle, bus, truck

vehicle_memory = {}

def extract_dynamic_features(frame, fps):
    roi = crop_roi(frame)

    results = model.track(
        roi,
        persist=True,
        tracker="botsort.yaml",
        classes=VEHICLE_CLASSES,
        conf=0.15,
        verbose=False
    )

    boxes = results[0].boxes
    if boxes.id is None:
        return None, results

    ids = boxes.id.cpu().numpy()
    xyxy = boxes.xyxy.cpu().numpy()

    speeds = []
    accelerations = []
    headings = []
    centers = []

    # --- Per vehicle ---
    for i, vid in enumerate(ids):
        cx = (xyxy[i][0] + xyxy[i][2]) / 2
        cy = (xyxy[i][1] + xyxy[i][3]) / 2
        centers.append((cx, cy))

        if vid in vehicle_memory:
            prev = vehicle_memory[vid]

            dx = cx - prev["x"]
            dy = cy - prev["y"]

            distance = np.sqrt(dx**2 + dy**2)
            speed = distance * fps  # px/sec
            accel = (speed - prev["speed"]) * fps
            heading = np.arctan2(dy, dx)

            speeds.append(speed)
            accelerations.append(accel)
            headings.append(heading)

            vehicle_memory[vid].update({
                "x": cx,
                "y": cy,
                "speed": speed,
                "heading": heading
            })
        else:
            vehicle_memory[vid] = {
                "x": cx,
                "y": cy,
                "speed": 0,
                "heading": 0
            }

    # --- Inter-vehicle distance ---
    min_distance = np.inf
    for i in range(len(centers)):
        for j in range(i+1, len(centers)):
            d = np.linalg.norm(
                np.array(centers[i]) - np.array(centers[j])
            )
            min_distance = min(min_distance, d)

    features = {
        "vehicle_count": len(ids),
        "avg_speed": np.mean(speeds) if speeds else 0,
        "avg_acceleration": np.mean(np.abs(accelerations)) if accelerations else 0,
        "heading_variance": np.std(headings) if headings else 0,
        "min_distance": min_distance if min_distance != np.inf else 0,
        "speed_variance": np.std(speeds) if speeds else 0
    }

    return features, results

feature_log = []
risk_scores = []

for frame in tqdm(frames, desc="Processing Frames"):
    features, results = extract_dynamic_features(frame, fps)

    if features is None:
        continue

    # --- Risk Score (Pre-Accident) ---
    risk = (
        0.25 * features["vehicle_count"] +
        0.25 * features["avg_acceleration"] +
        0.2  * features["heading_variance"] +
        0.2  * (1 / (features["min_distance"] + 1)) +
        0.1  * features["speed_variance"]
    )

    features["risk"] = risk
    feature_log.append(features)
    risk_scores.append(risk)

df = pd.DataFrame(feature_log)
df.head()

plt.figure(figsize=(10,4))
plt.plot(risk_scores, color="red")
plt.title("Pre-Accident Risk Score Over Time")
plt.xlabel("Time (seconds)")
plt.ylabel("Risk Level")
plt.show()

annotated = results[0].plot()
annotated_rgb = cv2.cvtColor(annotated, cv2.COLOR_BGR2RGB)

plt.figure(figsize=(8,6))
plt.imshow(annotated_rgb)
plt.axis("off")
plt.show()

df.columns

X = df[
    [
        "vehicle_count",
        "avg_speed",
        "avg_acceleration",
        "heading_variance",
        "min_distance",
        "speed_variance",
    ]
]

y = df["risk_label"]



from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.25,
    random_state=42,
    stratify=y
)

from sklearn.linear_model import LogisticRegression

log_model = LogisticRegression(
    max_iter=1000,
    multi_class="multinomial"
)

log_model.fit(X_train, y_train)

from sklearn.tree import DecisionTreeClassifier

dt_model = DecisionTreeClassifier(
    max_depth=6,
    random_state=42
)

dt_model.fit(X_train, y_train)

from sklearn.ensemble import RandomForestClassifier

rf_model = RandomForestClassifier(
    n_estimators=200,
    max_depth=8,
    random_state=42
)

rf_model.fit(X_train, y_train)

from sklearn.metrics import classification_report, accuracy_score

y_pred_log = log_model.predict(X_test)
print("Logistic Regression")
print(classification_report(y_test, y_pred_log))

y_pred_dt = dt_model.predict(X_test)
print("Decision Tree")
print(classification_report(y_test, y_pred_dt))

y_pred_rf = rf_model.predict(X_test)
print("Random Forest")
print(classification_report(y_test, y_pred_rf))

models = {
    "Logistic": accuracy_score(y_test, y_pred_log),
    "Decision Tree": accuracy_score(y_test, y_pred_dt),
    "Random Forest": accuracy_score(y_test, y_pred_rf)
}

pd.DataFrame.from_dict(models, orient="index", columns=["Accuracy"])

pred_class = rf_model.predict(X_test)

def risk_label(c):
    if c == 0:
        return "LOW"
    elif c == 1:
        return "MEDIUM"
    else:
        return "HIGH"

risk_levels = [risk_label(c) for c in pred_class]
risk_levels[:10]

proba = rf_model.predict_proba(X_test)

risk_percent = (
    proba[:,1] * 50 +   # Medium
    proba[:,2] * 100    # High
)

risk_percent[:10]

results = pd.DataFrame({
    "Risk_Level": risk_levels,
    "Risk_Percent": risk_percent
})

results.head()

import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import PolynomialFeatures
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error

# توليد داتا بسيطة
np.random.seed(42)
X = np.linspace(-3, 3, 30).reshape(-1, 1)
y = np.sin(X) + np.random.normal(0, 0.2, X.shape)

# تقسيم Train / Test
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.3, random_state=42
)

# موديل معقّد (Polynomial عالي الدرجة)
poly = PolynomialFeatures(degree=15)
X_train_poly = poly.fit_transform(X_train)
X_test_poly = poly.transform(X_test)

model = LinearRegression()
model.fit(X_train_poly, y_train)

# التوقعات
y_train_pred = model.predict(X_train_poly)
y_test_pred = model.predict(X_test_poly)

# حساب الخطأ
train_error = mean_squared_error(y_train, y_train_pred)
test_error = mean_squared_error(y_test, y_test_pred)

print("Train MSE:", train_error)
print("Test MSE :", test_error)

# رسم النتيجة
X_plot = np.linspace(-3, 3, 200).reshape(-1, 1)
X_plot_poly = poly.transform(X_plot)
y_plot = model.predict(X_plot_poly)

plt.scatter(X_train, y_train, color='blue', label='Train data')
plt.scatter(X_test, y_test, color='red', label='Test data')
plt.plot(X_plot, y_plot, color='black', label='Overfitted model')
plt.legend()
plt.title("Overfitting Example")
plt.show()

import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import PolynomialFeatures
from sklearn.linear_model import Ridge
from sklearn.metrics import mean_squared_error

# توليد نفس الداتا
np.random.seed(42)
X = np.linspace(-3, 3, 30).reshape(-1, 1)
y = np.sin(X) + np.random.normal(0, 0.2, X.shape)

# تقسيم Train / Test
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.3, random_state=42
)

# تقليل التعقيد + Regularization
poly = PolynomialFeatures(degree=5)
X_train_poly = poly.fit_transform(X_train)
X_test_poly = poly.transform(X_test)

model = Ridge(alpha=1.0)  # L2 Regularization
model.fit(X_train_poly, y_train)

# التوقعات
y_train_pred = model.predict(X_train_poly)
y_test_pred = model.predict(X_test_poly)

# حساب الخطأ
train_error = mean_squared_error(y_train, y_train_pred)
test_error = mean_squared_error(y_test, y_test_pred)

print("Train MSE:", train_error)
print("Test MSE :", test_error)

# رسم النتيجة الجديدة
X_plot = np.linspace(-3, 3, 200).reshape(-1, 1)
X_plot_poly = poly.transform(X_plot)
y_plot = model.predict(X_plot_poly)

plt.scatter(X_train, y_train, color='blue', label='Train data')
plt.scatter(X_test, y_test, color='red', label='Test data')
plt.plot(X_plot, y_plot, color='green', label='Regularized model')
plt.legend()
plt.title("Overfitting Fixed Using Regularization")
plt.show()

import numpy as np
import cv2
import matplotlib.pyplot as plt
from sklearn.preprocessing import PolynomialFeatures
from sklearn.linear_model import Ridge

# ===== 1. تدريب الموديل =====
X = np.linspace(0, 10, 50).reshape(-1, 1)
y = np.sin(X)

poly = PolynomialFeatures(degree=5)
X_poly = poly.fit_transform(X)

model = Ridge(alpha=1.0)
model.fit(X_poly, y)

# ===== 2. فتح الفيديو =====
video_path = "/kaggle/input/traffic-video-dataset/Talaimari/east.mp4"
cap = cv2.VideoCapture(video_path)

print("Video opened:", cap.isOpened())

predictions = []
frames = []

frame_id = 0
max_frames = 150   # عدد فريمات معقول

# ===== 3. قراءة الفيديو + Predictions =====
while cap.isOpened() and frame_id < max_frames:
    ret, frame = cap.read()
    if not ret:
        break

    x_input = np.array([[frame_id / 10]])
    x_poly = poly.transform(x_input)
    pred = model.predict(x_poly)[0][0]

    predictions.append(pred)
    frames.append(frame_id)

    frame_id += 1

cap.release()

print("Total frames processed:", len(predictions))

n = min(10, len(predictions))
for i in range(n):
    print(f"Frame {frames[i]} → Prediction = {predictions[i]:.3f}")

plt.figure(figsize=(8,4))
plt.plot(frames, predictions, marker='o')
plt.xlabel("Frame Index")
plt.ylabel("Model Prediction")
plt.title("Model Predictions on Video Frames")
plt.grid(True)
plt.show()

import numpy as np
from sklearn.preprocessing import PolynomialFeatures
from sklearn.linear_model import Ridge
import joblib

# Training data
X = np.linspace(0, 10, 50).reshape(-1, 1)
y = np.sin(X)

poly = PolynomialFeatures(degree=5)
X_poly = poly.fit_transform(X)

model = Ridge(alpha=1.0)
model.fit(X_poly, y)

# حفظ الموديل والـ transformer
joblib.dump(model, "ridge_model.pkl")
joblib.dump(poly, "poly_transformer.pkl")

import joblib

model = joblib.load("ridge_model.pkl")
poly = joblib.load("poly_transformer.pkl")

# قيم جديدة الموديل ما شافهاش
X_new = np.array([[1.5], [2.0], [3.2]])

X_new_poly = poly.transform(X_new)
predictions = model.predict(X_new_poly)

for x, p in zip(X_new, predictions):
    print(f"Input {x[0]} → Prediction {p[0]:.3f}")

import cv2

video_path = "/kaggle/input/traffic-video-dataset/Talaimari/east.mp4"
cap = cv2.VideoCapture(video_path)

frame_id = 0

while cap.isOpened() and frame_id < 20:
    ret, frame = cap.read()
    if not ret:
        break

    x_input = np.array([[frame_id / 10]])
    x_poly = poly.transform(x_input)
    pred = model.predict(x_poly)[0][0]

    print(f"Frame {frame_id} → Prediction {pred:.3f}")
    frame_id += 1

cap.release()

import numpy as np
from sklearn.preprocessing import PolynomialFeatures
from sklearn.linear_model import Ridge
import joblib

# 1. Training data
X = np.linspace(0, 10, 50).reshape(-1, 1)
y = np.sin(X)

# 2. Polynomial transform
poly = PolynomialFeatures(degree=5)
X_poly = poly.fit_transform(X)

# 3. Train model
model = Ridge(alpha=1.0)
model.fit(X_poly, y)

# 4. Save model & transformer
joblib.dump(model, "ridge_model.pkl")
joblib.dump(poly, "poly_transformer.pkl")

print("Model and transformer saved successfully ✅")